### ISSUE TITLE
v5 Use an experimental feature

### ISSUE THREAD

**Issue by exos** [sindresorhus/strip-bom#15]
The compatibility with node 12 is breaking because the "ECMAScript modules" is an experimental feature in this version, the projects that depdends of this package need to force use it, or adapt they project.

```
/home/exos/example/node_modules/strip-bom/index.js:1
export default function stripBom(string) {
^^^^^^

SyntaxError: Unexpected token 'export'
    at Module._compile (internal/modules/cjs/loader.js:892:18)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:849:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/exos/example/lib/services/contents.js:75:40)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:849:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/exos/example/lib/services/index.js:18:40)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:849:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/exos/example/lib/tasks/start.js:10:40)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
```

Others implementations breaks too:

```
  ● Test suite failed to run

    Jest encountered an unexpected token

    This usually means that you are trying to import a file which Jest cannot parse, e.g. it's not plain JavaScript.

    By default, if Jest sees a Babel config, it will use that to transform your files, ignoring "node_modules".

    Here's what you can do:
     • If you are trying to use ECMAScript Modules, see https://jestjs.io/docs/en/ecmascript-modules for how to enable it.
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/en/configuration.html

    Details:

    /home/exos/example/node_modules/strip-bom/index.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){export default function stripBom(string) {
                                                                                             ^^^^^^

    SyntaxError: Unexpected token 'export'

      20 | import config from '../config';
      21 | import subsrt from 'subsrt';
    > 22 | import stripBom from 'strip-bom';
         | ^
      23 |

      at Runtime.createScriptFromCode (node_modules/jest-runtime/build/index.js:1350:14)
      at Object.<anonymous> (src/services/contents.js:22:1)

```

I recommend you to use babel, or move this release to a flag like `strip-bom@es`.

**workaround**, use v4:

```
npm install --save strip-bom@^4
```

or

```
yarn add strip-bom@^4
```

PS. sorry my poor english

**Comment by sindresorhus** [comment]
Please read the release notes. You need a newer version of Node.js 12.

**Comment by exos** [comment]
Upgrade package.json

```
	"engines": {
		"node": ">=12"
	},
```
